Repository dragonflyoss/community, pull requests merged in 2025-09, with the labels that each got.

#78 docs: add membership application template for community roles
  .github/ISSUE_TEMPLATE/departure.md
  .github/ISSUE_TEMPLATE/election.md
  .github/ISSUE_TEMPLATE/nominate.md
  .gitvote.yml
  COMMUNITY_LADDER.md
  COMMUNITY_MEMBERSHIP.md
  GOVERNANCE.md
  MAINTAINERS.md
  roles/Approvers.md
  roles/Community-Managers.md
  roles/Maintainers.md
  roles/Members.md
  roles/Security-Team.md
Labels: enhancement, document

#94 fix: should use --recurse-submodules to clone
  CONTRIBUTING.md
Labels: enhancement

#96 docs(README): update community and governance sections
  README.md
Labels: documentation

#95 docs: expand community membership with CNCF and governance processes
  COMMUNITY_MEMBERSHIP.md
Labels: community, documentation, cncf-request, governance-change

#102 docs(community): update membership process formatting
  COMMUNITY_MEMBERSHIP.md
  REPOSITORIES.md
Labels: documentation

#104 docs: update community roles and responsibilities
  COMMUNITY_LADDER.md
  CONTRIBUTING.md
  GOVERNANCE.md
  releases/2.3.0/README.md
  roles/Members.md
  roles/README.md
Labels: enhancement

#105 docs(meetings): add README for maintainer meeting on 2025-09-23
  meetings/maintainer/2025-09-23/README.md
Labels: weekly-digest
