Repository dragonflyoss/community, pull requests merged in 2025-06, with the labels that each got.

#39 docs: update meeting details and add 2025-06-17 maintainer meeting notes
  README.md
  meetings/maintainer/2025-06-17/README.md
  meetings/nydus/maintainer/.gitkeep
Labels: document

#38 add contributor ladder and roles documentation 📝
  COMMUNITY_LADDER.md
  COMMUNITY_MEMBERSHIP.md
  ladder/emeritus_members.yaml
Labels: enhancement, document

#40 docs: add roles for community manager
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  COMMUNITY_MEMBERSHIP.md
  meetings/maintainer/2025-06-17/README.md
  roles/Community-Managers.md
Labels: document

#41 docs: Update records for 2025-06-17 Maintainer Meeting with attendees, issues, and actions
  meetings/maintainer/2025-06-17/README.md
Labels: enhancement

#45 docs(releases): Add release notes for v2.3.0
  releases/2.3.0/README.md
  releases/2.3.0/images/dragonfly-linear.png
  releases/2.3.0/images/p1.webp
  releases/2.3.0/images/p10.webp
  releases/2.3.0/images/p11.webp
  releases/2.3.0/images/p12.webp
  releases/2.3.0/images/p13.webp
  releases/2.3.0/images/p2.webp
  releases/2.3.0/images/p3.webp
  releases/2.3.0/images/p4.webp
  releases/2.3.0/images/p5.webp
  releases/2.3.0/images/p6.webp
  releases/2.3.0/images/p7.webp
  releases/2.3.0/images/p8.webp
  releases/2.3.0/images/p9.webp
Labels: document
